# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Деревянкин Владислав Владимирович
- ОЗИВТ(ППК)-22-2-у

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |
| Задание 6 | - | - |
| Задание 7 | - | - |
| Задание 8 | - | - |
| Задание 9 | - | - |
| Задание 10 | - | - |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа №1
### Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто “возьмёт их из этого декоратора”). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи.

```python
from functools import lru_cache


@lru_cache(None)
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)

if __name__ == '__main__':
    print(fibonacci(100))
```

### Результат.
![image](https://github.com/che3ZzOfficial/Program_engineering/assets/122799788/c65bbea9-f90c-46e6-b659-4e627f7cf06b)


## Выводы
Без декоратора вообще не выводит число.

## Лабораторная работа №2
### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130. Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.

```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name, age)

    return output_func

@check
def personal_info(name, age):
    print(f"Name: {name} Age: {age}")

if __name__ == '__main__':
    personal_info('Владимир', 38)
    personal_info('Александр', -5)
    personal_info('Петр', 138, 15, 48, 2)

```
### Результат.
![image](https://github.com/che3ZzOfficial/Program_engineering/assets/122799788/606bd3e6-b8aa-4a9a-be3f-8faab5e22a02)

## Выводы

Использовали декоратор для проверки условия.

## Лабораторная работа №3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.

```python
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')

if __name__ == '__main__':
    data([1, 15, 'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])
```
### Результат.
![image](https://github.com/che3ZzOfficial/Program_engineering/assets/122799788/8d79ef87-523e-461d-84e2-e89e9f00fc12)

## Выводы

Остановили хацкера за счёт обработчика ошибок.


## Лабораторная работа №4
### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться “Успешная регистрация”.
```python
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name) > 10:
        raise NegativeValueException('Длина более 10 символов')
    else:
        print('Успешная регистрация')

if __name__ == '__main__':
    name = '1234567891'
    check_name(name)
```
### Результат.
![image](https://github.com/che3ZzOfficial/Program_engineering/assets/122799788/ade3ff17-cad6-4d33-bd71-1f58a092b3c3)


## Выводы

теперь уже обработчик исключений.

## Лабораторная работа №5
### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: __init__() (вызывается при создании класса декоратора в программе) и __call__() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.

```python
class SiteChecker:
    def __init__(self, func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('> Проверка перед запууском', self.func.__name__)
        self.func()
        print('> Проверка безопасного выключения')


@SiteChecker
def site():
    print('Усердная работа сайта')

if __name__ == '__main__':
    print('>> Сайт запущен')
    site()
    print('>> Сайт выключен')
```
### Результат.
![image](https://github.com/che3ZzOfficial/Program_engineering/assets/122799788/6fe05537-1367-4725-8dd0-eb0a1f3ad0c9)


## Выводы

Теперь используем декоратор в виде логгера чтобы вывести все логи в консоль

## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.

```python
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"\nФункция {func.__name__} выполнилась за {execution_time:.5f} секунд")
        return result
    return wrapper

@timing_decorator
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```
### Результат.
![image](https://github.com/che3ZzOfficial/Program_engineering/assets/122799788/4089bea9-fb19-4c55-8aad-14e5bebeddde)

## Выводы

Помогаем вовочке сделать секундомер замерения выполнения программы.

## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def read_file(file_path):
    try:
        with open(file_path, 'r') as file:
            data = file.read()
            if not data:
                raise Exception("Файл пустой")
            else:
                print("Информация из файла:")
                print(data)
    except FileNotFoundError:
        print(f"Файл {file_path} не найден")
    except Exception as e:
        print(f"Ошибка: {e}")


empty_file_path = "empty_file.txt"
open(empty_file_path, 'w').close()

non_empty_file_path = "non_empty_file.txt"
with open(non_empty_file_path, 'w') as file:
    file.write("Hello world.")

print("\nПопытка чтения пустого файла:")
read_file('empty_file.txt')
print("\nПопытка чтения непустого файла:")
read_file('non_empty_file.txt')
```
### Результат.
![image](https://github.com/che3ZzOfficial/Program_engineering/assets/122799788/0265c75e-876a-4017-923d-aebb4e13e1d9)

## Выводы

Работаем с файлами и их форматом.
  
## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль.

```python
def add_two_and_input():
    try:
        user_input = input("Введите число: ")
        result = 2 + float(user_input)
        print(f"Результат сложения 2 и введенного числа: {result}")
    except ValueError:
        print("Ошибка: Неподходящий тип данных. Ожидалось число.")

add_two_and_input()
add_two_and_input()
add_two_and_input()
```
### Результат.
![image](https://github.com/che3ZzOfficial/Program_engineering/assets/122799788/478a91a1-57a1-47b5-8402-73d078ab4ba7)


## Выводы

написали функцию и сделали обработчик ошибок под него чтобы ошибку не выдавало.
  
## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
def dd(func): # создаём новый метод в котором будет вложенный метод с проверкой
    def wrapper(*args, **kwargs):
        print(f"Декоратор: Вызывается функция {func.__name__}") # запрашивается функция
        result = func(*args, **kwargs) # выполнение функции
        print(f"Декоратор: Функция {func.__name__} выполнена") # отписка что функция выполнена
        return result # возвращаем результат.
    return wrapper
@dd # первая функция
def add_numbers(a, b):
    return a / b

@dd # вторая функция
def multiply_numbers(a, b):
    return a ** b

result_sum = add_numbers(2, 3) # данные
print(f"Результат сложения: {result_sum}") # вывод в консоль

result_product = multiply_numbers(4, 5)# данные
print(f"Результат умножения: {result_product}") # вывод в консоль
```
### Результат.
![image](https://github.com/che3ZzOfficial/Program_engineering/assets/122799788/68248a80-487c-42bc-ab6b-8192f6f9e18a)

## Выводы

Создали собственный декоратор который показывает его эффективность.
  
## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class CustomException(Exception):
    pass

# Code snippet 1
def divide_numbers(a, b):
    if b == 0:
        raise CustomException("Нельзя делить на ноль")
    return a / b

try:
    result = divide_numbers(10, 0)
    print("Результат:", result)
except CustomException as e:
    print("Ошибка:", str(e))

# Code snippet 2
def process_data(data):
    if not data:
        raise CustomException("Данные не предоставлены")
    # Process the data here

try:
    process_data([])
except CustomException as e:
    print("Ошибка:", str(e))
```
### Результат.
![image](https://github.com/che3ZzOfficial/Program_engineering/assets/122799788/f03341b6-05d7-4ebe-b114-e8bc8f543e6d)

  
## Выводы

Создали собственный обработчик исключений


## Общие выводы по теме
Декораторы очень сильно помогают в создании приложений или игр чтобы не было error в ей самой.
